/**
 * ScheduleContainer component - orchestrates the appointment scheduling flow
 *
 * Main container component that brings together the calendar, time slot picker,
 * and session details to create a complete scheduling experience. Manages
 * state for date/time selection and coordinates data fetching.
 *
 * Features:
 * - Two-step selection: date then time
 * - Session details sidebar (desktop) or header (mobile)
 * - "Confirm Booking" button (enabled when time selected)
 * - "Back to Matching" navigation
 * - Real-time availability updates
 * - Loading and error states
 *
 * Layout:
 * - Desktop: Calendar + Time slots (left) | Session details (right sidebar)
 * - Mobile: Stacked layout with session details at top
 *
 * Visual Design:
 * - Cream background
 * - Teal primary actions
 * - Clear visual hierarchy
 *
 * Accessibility:
 * - Logical tab order
 * - ARIA live regions for updates
 * - Keyboard navigable
 */
"use client";

import * as React from "react";
// import { useSuspenseQuery } from "@apollo/client"; // Will be used when GraphQL schema is ready
import { ArrowLeft, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { AppointmentCalendar } from "./AppointmentCalendar";
import { TimeSlotPicker, type TimeSlot } from "./TimeSlotPicker";
import { SessionDetails } from "./SessionDetails";
import { useDetectedTimezone } from "./TimezoneSelector";
// Note: GraphQL import will be auto-generated by codegen
// For now, this is a placeholder - the actual import will be:
// import { GetTherapistAvailabilityDocument } from '@/types/graphql';
const GET_THERAPIST_AVAILABILITY = null as any; // Placeholder until codegen runs

/**
 * Props for ScheduleContainer component
 * @param therapistId - ID of the selected therapist
 * @param therapistName - Name of the therapist
 * @param therapistPhotoUrl - URL to therapist's photo
 * @param onBack - Callback when "Back to Matching" is clicked
 * @param onConfirmBooking - Callback when booking is confirmed with selected slot
 * @param sessionId - Current onboarding session ID
 * @param className - Optional additional CSS classes
 */
export interface ScheduleContainerProps {
  therapistId: string;
  therapistName: string;
  therapistPhotoUrl?: string;
  onBack: () => void;
  onConfirmBooking: (slot: TimeSlot, timezone: string) => void;
  sessionId?: string;
  className?: string;
}

/**
 * Orchestrates the appointment scheduling flow with calendar and time selection
 *
 * State Management:
 * - Selected date (calendar)
 * - Selected time slot
 * - User timezone (with auto-detection)
 *
 * Data Fetching:
 * - GraphQL query for therapist availability
 * - Refetch on timezone change
 * - Loading and error states
 *
 * @example
 * <ScheduleContainer
 *   therapistId="123"
 *   therapistName="Dr. Sarah Johnson"
 *   onBack={() => router.push('/matching')}
 *   onConfirmBooking={(slot, tz) => handleBooking(slot, tz)}
 * />
 */
export function ScheduleContainer({
  therapistId,
  therapistName,
  therapistPhotoUrl,
  onBack,
  onConfirmBooking,
  sessionId,
  className,
}: ScheduleContainerProps) {
  // State
  const [selectedDate, setSelectedDate] = React.useState<Date | undefined>();
  const [selectedSlot, setSelectedSlot] = React.useState<TimeSlot | undefined>();
  const detectedTimezone = useDetectedTimezone();
  const [timezone, setTimezone] = React.useState<string>(detectedTimezone);

  // Update timezone when detection completes
  React.useEffect(() => {
    if (detectedTimezone) {
      setTimezone(detectedTimezone);
    }
  }, [detectedTimezone]);

  /**
   * Calculate date range for availability query
   * Start: today, End: 3 months from today
   */
  const dateRange = React.useMemo(() => {
    const startDate = new Date();
    const endDate = new Date();
    endDate.setMonth(endDate.getMonth() + 3);

    return {
      startDate: startDate.toISOString(),
      endDate: endDate.toISOString(),
    };
  }, []);

  /**
   * Fetch therapist availability
   * Note: This will error until GraphQL schema is implemented
   * For now, we're setting up the structure
   */
  // Note: Using conditional rendering instead of useSuspenseQuery until GraphQL schema is implemented
  // Uncomment when backend is ready:
  // const { data, loading, error } = useSuspenseQuery(GET_THERAPIST_AVAILABILITY, {

  // Temporary mock data structure for development
  const { data, loading, error } = React.useMemo(() => ({
    data: null,
    loading: false,
    error: null,
  }), []);

  /* Real implementation (uncomment when backend ready):
  const { data, loading, error } = useSuspenseQuery(GET_THERAPIST_AVAILABILITY, {
    variables: {
      therapistId,
      startDate: dateRange.startDate,
      endDate: dateRange.endDate,
      timezone,
    },
    skip: !therapistId,
    // Refetch when timezone changes
    fetchPolicy: "cache-and-network",
  });
  */

  /**
   * Extract available dates from query response
   */
  const availableDates = React.useMemo(() => {
    if (!data || !(data as any)?.therapistAvailability?.availableDates) return [];

    return (data as any).therapistAvailability.availableDates
      .filter((d: any) => d.hasAvailability)
      .map((d: any) => new Date(d.date));
  }, [data]);

  /**
   * Get time slots for selected date
   */
  const timeSlotsForSelectedDate = React.useMemo(() => {
    if (!selectedDate || !data || !(data as any)?.therapistAvailability?.availableDates) {
      return [];
    }

    const dateStr = selectedDate.toISOString().split("T")[0];
    const dateData = (data as any).therapistAvailability.availableDates.find(
      (d: any) => d.date.startsWith(dateStr)
    );

    return dateData?.slots || [];
  }, [selectedDate, data]);

  /**
   * Handle date selection from calendar
   * Reset selected slot when date changes
   */
  const handleDateSelect = React.useCallback((date: Date | undefined) => {
    setSelectedDate(date);
    setSelectedSlot(undefined); // Reset time slot when date changes
  }, []);

  /**
   * Handle time slot selection
   */
  const handleSlotSelect = React.useCallback((slot: TimeSlot) => {
    setSelectedSlot(slot);
  }, []);

  /**
   * Handle timezone change
   * Reset selections as times will change
   */
  const handleTimezoneChange = React.useCallback((newTimezone: string) => {
    setTimezone(newTimezone);
    setSelectedDate(undefined);
    setSelectedSlot(undefined);
  }, []);

  /**
   * Handle confirm booking button click
   */
  const handleConfirmBooking = React.useCallback(() => {
    if (selectedSlot) {
      onConfirmBooking(selectedSlot, timezone);
    }
  }, [selectedSlot, timezone, onConfirmBooking]);

  /**
   * Check if booking can be confirmed
   */
  const canConfirmBooking = Boolean(selectedDate && selectedSlot);

  return (
    <div className={cn("min-h-screen bg-cream/50", className)}>
      {/* Header with Back Button */}
      <div className="border-b border-gray-200 bg-white">
        <div className="container mx-auto px-4 py-4">
          <Button
            variant="ghost"
            onClick={onBack}
            className="text-daybreak-teal hover:text-daybreak-teal/80 hover:bg-daybreak-teal/10"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Matching
          </Button>
        </div>
      </div>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-8">
        {/* Page Title */}
        <div className="mb-8 text-center">
          <h1 className="text-3xl font-bold font-serif text-deep-text mb-2">
            Schedule Your First Session
          </h1>
          <p className="text-muted-foreground">
            Select a convenient date and time for your appointment
          </p>
        </div>

        {/* Layout: Sidebar (Desktop) / Stacked (Mobile) */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left Column: Calendar + Time Slots */}
          <div className="lg:col-span-2 space-y-6">
            {/* Calendar */}
            <AppointmentCalendar
              availableDates={availableDates}
              selectedDate={selectedDate}
              onDateSelect={handleDateSelect}
            />

            {/* Time Slots (only show when date selected) */}
            {selectedDate && (
              <div role="region" aria-live="polite" aria-atomic="true">
                {loading ? (
                  <div className="flex items-center justify-center py-12">
                    <Loader2 className="h-8 w-8 animate-spin text-daybreak-teal" />
                    <span className="ml-3 text-muted-foreground">
                      Loading available times...
                    </span>
                  </div>
                ) : (
                  <TimeSlotPicker
                    slots={timeSlotsForSelectedDate}
                    selectedSlot={selectedSlot}
                    onSlotSelect={handleSlotSelect}
                    timezone={timezone}
                  />
                )}
              </div>
            )}

            {/* Error State */}
            {error && (
              <div
                className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"
                role="alert"
              >
                <p className="font-medium">Unable to load availability</p>
                <p className="mt-1 text-xs">
                  Please try again or contact support if the problem persists.
                </p>
              </div>
            )}
          </div>

          {/* Right Column: Session Details Sidebar */}
          <div className="lg:col-span-1">
            <div className="lg:sticky lg:top-6">
              <SessionDetails
                therapistName={therapistName}
                therapistPhotoUrl={therapistPhotoUrl}
                sessionDuration={50}
                sessionType="video"
                timezone={timezone}
                onTimezoneChange={handleTimezoneChange}
              />

              {/* Confirm Booking Button */}
              <Button
                onClick={handleConfirmBooking}
                disabled={!canConfirmBooking || loading}
                className="w-full mt-6 bg-daybreak-teal hover:bg-daybreak-teal/90 text-white disabled:opacity-50 disabled:cursor-not-allowed"
                size="lg"
              >
                {canConfirmBooking ? "Confirm Booking" : "Select Date & Time"}
              </Button>

              {/* Selection Summary */}
              {selectedDate && selectedSlot && (
                <div
                  className="mt-4 p-4 rounded-lg bg-green-50 border border-green-200"
                  role="status"
                  aria-live="polite"
                >
                  <p className="text-sm font-medium text-green-800">
                    Ready to book!
                  </p>
                  <p className="text-xs text-green-700 mt-1">
                    {selectedDate.toLocaleDateString("en-US", {
                      weekday: "long",
                      month: "long",
                      day: "numeric",
                      year: "numeric",
                    })}{" "}
                    at{" "}
                    {new Date(selectedSlot.startTime).toLocaleTimeString(
                      "en-US",
                      {
                        hour: "numeric",
                        minute: "2-digit",
                        hour12: true,
                        timeZone: timezone,
                      }
                    )}
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

ScheduleContainer.displayName = "ScheduleContainer";
