/**
 * Custom hook for fetching comprehensive cost comparison data
 *
 * Provides a unified interface for components to access all cost-related
 * data including insurance estimates, self-pay options, deductible tracking,
 * out-of-pocket progress, and insurance card images.
 *
 * Features:
 * - Combined query for cost comparison and session insurance data
 * - Deductible and out-of-pocket tracking integration
 * - Insurance card image URLs for display
 * - Recommendation and savings data
 * - Loading and error state management
 * - Apollo cache integration
 *
 * Security:
 * - Session-scoped data access
 * - No PHI logging
 * - Presigned URLs for card images (15-min expiry)
 */

import { useQuery } from "@apollo/client/react";
import { useMemo } from "react";

// Note: These imports will be auto-generated by GraphQL Code Generator
// For now, this is a placeholder until codegen runs
// The actual import will be:
// import { GetEnhancedCostComparisonDocument } from '@/types/graphql';
const GET_ENHANCED_COST_COMPARISON = null as unknown as any; // Placeholder until codegen runs

/**
 * Insurance estimate data structure
 */
export interface InsuranceEstimateData {
  perSessionCost: string;
  totalEstimatedCost: string;
  explanation: string;
  assumptionNotes: string[];
}

/**
 * Package option data structure
 */
export interface PackageOptionData {
  sessions: number;
  totalPrice: string;
  perSessionCost: string;
  savings: string;
  description: string;
}

/**
 * Self-pay estimate data structure
 */
export interface SelfPayEstimateData {
  baseRate: string;
  totalForTypicalTreatment: string;
  slidingScaleInfo: string | null;
  transparentPricingMessage: string;
  whatIsIncluded: string[];
  whatIsNotIncluded: string[];
  packageOptions: PackageOptionData[];
}

/**
 * Comparison table row structure
 */
export interface ComparisonRowData {
  label: string;
  insuranceValue: string | null;
  selfPayValue: string;
  highlightSelfPay: boolean;
}

/**
 * Deductible and out-of-pocket tracking data
 */
export interface DeductibleStatusData {
  amount: number;
  met: number;
  remaining: number;
  progressPercentage: number;
  isMet: boolean;
  oopMaxAmount: number | null;
  oopMet: number | null;
  oopRemaining: number | null;
  oopProgressPercentage: number | null;
}

/**
 * Insurance details from session
 */
export interface InsuranceDetailsData {
  cardImageFrontUrl: string | null;
  cardImageBackUrl: string | null;
  payerName: string | null;
  memberId: string | null;
  copayAmount: number | null;
  coinsurancePercentage: number | null;
  deductibleAmount: number | null;
  deductibleMet: number | null;
}

/**
 * Hook return type with all cost comparison data
 */
export interface UseCostComparisonResult {
  /** Insurance estimate (null if not verified) */
  insuranceEstimate: InsuranceEstimateData | null;
  /** Self-pay estimate (always available) */
  selfPayEstimate: SelfPayEstimateData | null;
  /** Pre-built comparison table rows */
  comparisonTable: ComparisonRowData[];
  /** Deductible and OOP tracking data */
  deductibleStatus: DeductibleStatusData | null;
  /** Insurance details including card images */
  insuranceDetails: InsuranceDetailsData | null;
  /** Personalized recommendation text */
  recommendation: string | null;
  /** Amount saved if choosing self-pay (in cents) */
  savingsIfSelfPay: number | null;
  /** Whether self-pay is the recommended option */
  highlightSelfPay: boolean;
  /** Loading state */
  loading: boolean;
  /** Error state */
  error: Error | null;
  /** Refetch function */
  refetch: () => void;
}

/**
 * Fetches comprehensive cost comparison data for a session
 *
 * Combines cost comparison query with session insurance data to provide
 * a unified view of all cost-related information. Used by the
 * EnhancedCostComparisonView component.
 *
 * @param sessionId - The onboarding session ID
 * @returns Combined cost comparison data with loading/error states
 *
 * @example
 * function CostPage({ sessionId }: { sessionId: string }) {
 *   const {
 *     insuranceEstimate,
 *     selfPayEstimate,
 *     deductibleStatus,
 *     recommendation,
 *     loading,
 *     error,
 *   } = useCostComparison(sessionId);
 *
 *   if (loading) return <LoadingState />;
 *   if (error) return <ErrorState error={error} />;
 *
 *   return (
 *     <EnhancedCostComparisonView
 *       insuranceEstimate={insuranceEstimate}
 *       selfPayEstimate={selfPayEstimate}
 *       deductibleStatus={deductibleStatus}
 *       recommendation={recommendation}
 *     />
 *   );
 * }
 */
export function useCostComparison(sessionId: string): UseCostComparisonResult {
  // Execute GraphQL query
  // Note: This will error until GraphQL schema is implemented
  const { data, loading, error, refetch } = useQuery(
    GET_ENHANCED_COST_COMPARISON || {},
    {
      variables: { sessionId },
      skip: !sessionId || !GET_ENHANCED_COST_COMPARISON,
      fetchPolicy: "cache-and-network", // Show cached data while fetching fresh
      errorPolicy: "all", // Return partial data on error
    }
  );

  /**
   * Extract and transform data from query response
   * Ensures type safety and handles missing data gracefully
   */
  const result = useMemo<Omit<UseCostComparisonResult, "loading" | "error" | "refetch">>(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const costComparison = (data as any)?.costComparison;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const deductibleStatusData = (data as any)?.deductibleStatus;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const sessionData = (data as any)?.session;

    return {
      insuranceEstimate: costComparison?.insuranceEstimate ?? null,
      selfPayEstimate: costComparison?.selfPayEstimate ?? null,
      comparisonTable: costComparison?.comparisonTable ?? [],
      deductibleStatus: deductibleStatusData ?? null,
      insuranceDetails: sessionData?.insurance ?? null,
      recommendation: costComparison?.recommendation ?? null,
      savingsIfSelfPay: costComparison?.savingsIfSelfPay ?? null,
      highlightSelfPay: costComparison?.highlightSelfPay ?? false,
    };
  }, [data]);

  /**
   * Wrap refetch to handle potential errors
   */
  const handleRefetch = () => {
    try {
      refetch();
    } catch (err) {
      // Error will be captured in error state
      console.error("Failed to refetch cost comparison:", err);
    }
  };

  return {
    ...result,
    loading,
    error: error ?? null,
    refetch: handleRefetch,
  };
}
